#!/bin/sh

[ $# -eq 0 ] || exit 1

${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	mydomain xmw.de
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	myorigin \$mydomain
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	inet_interfaces localhost
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	relayhost smtp.xmw.de
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	inet_protocols ipv4,ipv6
${PIRANHA:-piranha} check daemons/postfix/postalias root root@xmw.de
${PIRANHA:-piranha} check openrc/service postfix default
${PIRANHA:-piranha} check daemons/postfix/up




