#!/bin/sh

[ $# -eq 0 ] || exit 1

${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	mydomain fs.lmu.de
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	myorigin \$mydomain
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	inet_interfaces localhost
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	relayhost smtp.fs.lmu.de
${PIRANHA:-piranha} check daemons/postfix/postconf/unary \
	inet_protocols all
${PIRANHA:-piranha} check daemons/postfix/postalias root monitoring@fs.lmu.de
${PIRANHA:-piranha} check openrc/service postfix default
${PIRANHA:-piranha} check daemons/postfix/up




