#!/bin/sh

if [ -z "$PIRANHA" ] ; then
	export PIRANHA=$(realpath "$0")
	cd $(dirname $PIRANHA)
	export PIRANHA_LEVEL=""
else
	export PIRANHA_LEVEL="x ${PIRANHA_LEVEL}"
fi

mode=$1
shift 1

indent() {
	for i in ${PIRANHA_LEVEL} ; do
		echo -ne "\t"
	done
	if [ $# -ne 0 ] ; then
		echo -ne "$@"
	fi
} 

case "$mode" in
	check)
		if [ $# -eq 0 ] ; then
			cmd=hosts/$(hostname)
		else
			cmd=tests/$1
			shift 1
		fi
		if [ -d "$cmd" ] ; then
			stmt="$cmd/$mode $@"
			$cmd/$mode "$@"
		else
			stmt="$cmd $mode $@"
			$cmd $mode "$@"
		fi
		if [ $? -eq 0 ] ; then
			indent "$(tput setaf 2)passed$(tput sgr0) $stmt\n"
		else
			indent "$(tput setaf 1)failed$(tput sgr0) $stmt\n"
		fi
		;;
	pull)
		git pull
		;;
	*)
		echo "not implemented, try $(basename $0) (pull|check|...)"
		;;
esac
