#!/bin/sh

${PIRANHA:-piranha} check inittab/noclear tty1
${PIRANHA:-piranha} check sshd/upandrunning
${PIRANHA:-piranha} check sets/udev
${PIRANHA:-piranha} check sets/gentoo/lore
${PIRANHA:-piranha} check gentoo/pkg-dist-var

#gaf binhost
${PIRANHA:-piranha} check gentoo/portageq/envvar EMERGE_DEFAULT_OPTS "--keep-going --binpkg-respect-use y --getbinpkg y"
