#!/bin/sh

[ $# -eq 3 ] || exit 1

output=$(portageq repositories_configuration / | awk 'BEGIN {a=0} {if (substr($1, 0, 1)=="[") {a=0} ; if ($1=="['$1']") {a=1} ; if (a==1 && $1=="'$2'") {print $3}}')
[ "$output" == "$3" ]
