#!/bin/sh

[ $# -eq 0 ] || exit 1

${PIRANHA:-prianha} check sshd rhostsrsaauthentication no
${PIRANHA:-prianha} check sshd hostbasedauthentication no
${PIRANHA:-prianha} check sshd rsaauthentication yes
${PIRANHA:-prianha} check sshd pubkeyauthentication yes
${PIRANHA:-prianha} check sshd passwordauthentication no
${PIRANHA:-prianha} check sshd kbdinteractiveauthentication no
${PIRANHA:-prianha} check sshd challengeresponseauthentication no
